plugins:
  #
  # dns查询结果筛选
  #
  # 返回国内 ip 则 drop_resp
  - tag: drop_cn_ip_sequence
    type: sequence
    args:
      - matches: "resp_ip $ip_cn"
        exec: drop_resp

  # 返回非国内 ip 则 drop_resp
  - tag: drop_no_cn_ip_sequence
    type: sequence
    args:
      - matches: "!resp_ip $ip_cn"
        exec: drop_resp

  # 有响应终止查询并返回结果
  - tag: has_resp_sequence
    type: sequence
    args:
      # - exec: $modify_ttl
      # - matches: "resp_ip $ip_cloudflare"
      #   exec: black_hole www.cloudflare.com
      - matches: has_resp
        exec: accept

  # -------------------------------------------------------------------
  # -------------------------------------------------------------------
  #
  # fallback子序列
  #
  # 全栈域名 fallback，forward_gobal 优先
  - tag: fallback_dual_stlack_forward_gobal_sequence
    type: fallback
    args:
      primary: forward_gobal_ipv4_and_ipv6_ecs_gobal_sequence
      secondary: forward_local_ipv4_and_ipv6_ecs_gobal_sequence
      threshold: 400
      always_standby: false

  # 代理域名 fallback,prefer_ipv4，先remote查询，超时回gobal
  - tag: fallback_prefer_proxy_sequence
    type: fallback
    args:
      primary: forward_remote_ipv4_ecs_remote_sequence
      secondary: forward_gobal_ipv4_ecs_remote_sequence
      threshold: 800
      always_standby: false

  # 兜底域名 fallback，先remote查询，超时回gobal，ecs_local，检测查询结果是否为cn_ip
  - tag: fallback_final_detect_ip_sequence
    type: fallback
    args:
      primary: forward_gobal_ipv4_and_ipv6_ecs_local_sequence
      secondary: forward_remote_ipv4_and_ipv6_ecs_local_sequence
      threshold: 400
      always_standby: false

  # 兜底域名 fallback，prefer_ipv4，先remote查询，超时回gobal
  - tag: fallback_final_no_cn_ip_sequence
    type: fallback
    args:
      primary: forward_remote_ipv4_ecs_remote_sequence
      secondary: forward_gobal_ipv4_ecs_remote_sequence
      threshold: 800
      always_standby: false

  # -------------------------------------------------------------------
  # -------------------------------------------------------------------

  # -------------------------------------------------------------------
  # dns查询流程
  #
  # 屏蔽特定类型dns记录
  #
  - tag: query_reject
    type: sequence
    args:
      # 屏蔽反向查询
      - matches:
          - qtype 12
          - qname $local_ptr
        exec: reject 3
      # 屏蔽 ANY
      - matches: qtype 255
        exec: reject 3
      # 屏蔽private查询
      - matches:
          - qname $domain_private
        exec: reject 3
      # 屏蔽以下列表域名的HTTPS记录
      - matches:
          - qtype 65
          - "!qname { domain_dual_stlack_forward_local | domain_dual_stlack_forward_gobal | $domain_prefer_direct | domain_prefer_cn }"
        exec: reject 3

  # -------------------------------------------------------------------
  #
  # 域名全栈查询，无A/AAAA过滤，允许https等类型查询
  #
  # dual_stlack域名，cn，forward_local
  - tag: query_dual_stlack_forward_local
    type: sequence
    args:
      - matches: qname $domain_dual_stlack_forward_local
        exec: $forward_local_ipv4_and_ipv6_ecs_local_sequence

  # dual_stlack域名，gobal，gobal+cn
  - tag: query_dual_stlack_forward_gobal
    type: sequence
    args:
      - matches: qname $domain_dual_stlack_forward_gobal
        exec: $fallback_dual_stlack_forward_gobal_sequence

  # -------------------------------------------------------------------
  #
  # 域名prefer_ipv4/6查询，存在A/AAAA单栈过滤，可能存在https等类型过滤
  #
  # prefer_ipv4/6域名，代理，remote+gobal
  - tag: query_prefer_proxy
    type: sequence
    args:
      - matches: qname $domain_prefer_proxy
        exec: $fallback_prefer_proxy_sequence
      # 返回国内 ip 则 drop_resp
      - exec: $drop_cn_ip_sequence

  # prefer_ipv4/6域名，direct
  - tag: query_prefer_direct
    type: sequence
    args:
      - matches: qname $domain_prefer_direct
        # exec: $forward_local_ipv6_ecs_local_sequence
        exec: $forward_local_ipv4_and_ipv6_ecs_local_sequence

  # prefer_ipv4/6域名，gfw，remote+gobal
  - tag: query_prefer_gfw
    type: sequence
    args:
      - matches: qname $domain_prefer_gfw
        exec: $fallback_prefer_proxy_sequence
      # 返回国内 ip 则 drop_resp
      - exec: $drop_cn_ip_sequence

  # prefer_ipv4/6域名，cn
  - tag: query_prefer_cn
    type: sequence
    args:
      - matches: qname $domain_prefer_cn
        # exec: $forward_local_ipv6_ecs_local_sequence
        exec: $forward_local_ipv4_and_ipv6_ecs_local_sequence

  # -------------------------------------------------------------------
  #
  # 非域名列表内的域名查询，优先使用remote+gobal查询，避免dns泄露
  # forward_local禁止no_cn_ip记录响应，其它forward禁止cn_ip记录响应
  #
  # 兜底查询，fallback查询，仅允许no_cn_ip
  - tag: query_final_no_cn_ip
    type: sequence
    args:
      - exec: $fallback_final_no_cn_ip_sequence
      # 返回国内 ip 则 drop_resp
      - exec: $drop_cn_ip_sequence

  # # 兜底查询，fallback查询，仅允许no_cn_ip
  # - tag: query_final_no_cn_ip
  #   type: sequence
  #   args:
  #     # 使用ecs_local远程查询解析结果
  #     - exec: $fallback_final_detect_ip_sequence
  #     # 返回国内 ip 则 drop_resp
  #     - matches: has_resp
  #       exec: $drop_cn_ip_sequence
  #     # 返回非国内 ip 则 使用ecs_remote重新查询
  #     - matches: has_resp
  #       exec: $fallback_final_no_cn_ip_sequence

  # 兜底查询，cn查询，仅允许cn_ip
  - tag: query_final_cn_ip
    type: sequence
    args:
      - exec: $forward_local_ipv4_and_ipv6_ecs_local_sequence
      # 返回非国内 ip 则 drop_resp
      - exec: $drop_no_cn_ip_sequence

  # -------------------------------------------------------------------
  # -------------------------------------------------------------------
