log_file: "./updater.log"
rules_dir: "./rules"
download_dir: "./download"
mosdns_geo_set_dir: "../geo_set"
geoip_tags_url: "./tags/geoip_tags.txt"
geosite_tags_url: "./tags/geosite_tags.txt"
geoip_name: "geoip.dat"
geosite_name: "geosite.dat"
geoip_sha_name: "geoip.dat.sha256sum"
geosite_sha_name: "geosite.dat.sha256sum"
geoip_sha_dl_url: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat.sha256sum"
geosite_sha_dl_url: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat.sha256sum"
geoip_dl_url: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat"
geosite_dl_url: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
